server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/springboot-vue?useSSL=true&useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: "123456"
